s:
  image: tomcat:7-jre7
  volumes:
  - ./data/tomcat_logs:/usr/local/tomcat/logs
  - ./target/mdm-1.0-SNAPSHOT:/usr/local/tomcat/webapps/ROOT
  ports:
  - 8088:8080
  environment:
  - VIRTUAL_HOST=mdm.sklxsj.com
  - VIRTUAL_PORT=8080
  links:
  - m:mysql
m:
  image: mysql:5.7
  volumes:
  - ./data/mysql:/var/lib/mysql
  - ./server.cnf:/etc/mysql/conf.d/server.cnf
  environment:
  - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE